server:
  port: 8096

spring:
  application:
    name: demo-shopifyjava
  datasource:
    # url: jdbc:postgresql://localhost:5432/shopifyjava
    # username: postgres
    # password: Jay40984692
    # driverClassName: org.postgresql.Driver
    url: jdbc:mysql://localhost:3306/shopifyjava
    username: root
    password: Jay40984692$
    driverClassName: com.mysql.jdbc.Driver
  # redis:
  #   datasource:
  #     host: 127.0.0.1
  #     port: 6379
  #     username: redis
  #     password: admin1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

  # thymeleaf:
  #   prefix: classpath:/templates/
  #   suffix: .html
  #   mode: HTML

logging:
  level:
    org: WARN
    hibernate:
      SQL: DEBUG
      type:
        descriptor: TRACE
    blog: WARN
    # springframework:
    #   security: DEBUG
